on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository for GitHub Pages
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
          ssh-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      - name: Prepare Deployment
        run: |
          TARGET_PATH=${{ vars.DEPLOYMENT_PATH_PREFIX }}/${{ github.event.repository.name }}
          mkdir -p $TARGET_PATH
          rm -rf $TARGET_PATH/*
          cp -r ./dist/* $TARGET_PATH/
          rm -rf ./dist
      - name: Deploy to GitHub Pages repository
        run: |
          git status
          if git diff --quiet --exit-code && [[ -z "$(git ls-files --others --exclude-standard)" ]]; then
            echo 'No changes to deploy'
            exit 0
          fi
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"
          git add --all
          git commit -m "${{ vars.DEPLOYMENT_COMMIT_MESSAGE }}: ${{ github.repository }}@${{ github.sha }}"
          git push
