name: Deploy to Production

on:
  workflow_run:
    workflows: ["Deploy to Staging"]
    types:
      - completed

concurrency:
  group: deploy-to-production
  cancel-in-progress: true

jobs:
  deploy-production:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      artifact-run-id: ${{ github.event.workflow_run.id }}
      author-name: ${{ github.event.workflow_run.actor.login }}
      author-email: ${{ github.event.workflow_run.actor.id }}+${{ github.event.workflow_run.actor.login }}@users.noreply.github.com
    secrets: inherit
